//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDTAssignment2NWBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Account
    {
        public Account()
        {
            this.BillPays = new HashSet<BillPay>();
            this.Transactions = new HashSet<Transaction>();
            this.Transactions1 = new HashSet<Transaction>();
        }

        [Display(Name = "Account Number")]
        public int AccountNumber { get; set; }

        [Required(ErrorMessage = "Account type is required.")]
        [StringLength(1, MinimumLength = 1, ErrorMessage = "Account type cannot be longer than 1 character.")]
        [Display(Name = "Account Type")]
        public string AccountType { get; set; }

        [Required(ErrorMessage = "Balance is required.")]
        [RegularExpression(@"[-+]?[0-9]*\.?[0-9]?[0-9]", ErrorMessage = "Balance must be a number.")]
        public decimal Balance { get; set; }

        [Required(ErrorMessage = "Customer ID is required.")]
        [Display(Name = "Customer ID")]
        public int CustomerID { get; set; }

        [Display(Name = "Modified Date"), DataType(DataType.Date)]
        public System.DateTime ModifyDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual ICollection<BillPay> BillPays { get; set; }
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual ICollection<Transaction> Transactions1 { get; set; }

        /* Calculated fields. */
        public string AccountTypeNum
        {
            get
            {
                string acctTypeDesc = null;

                if (AccountType == "S")
                {
                    acctTypeDesc = "Savings";
                }
                else if (AccountType == "C")
                {
                    acctTypeDesc = "Checking";
                }
                else
                {
                    acctTypeDesc = AccountType;
                }
                return AccountType + " - " + acctTypeDesc + " - (Account No: " + AccountNumber + "; " + "Name: " + Customer.CustomerName + ")"; 
            }
        }
    }
}
