//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDTAssignment2NWBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using WDTAssignment2NWBA.BusinessLogicLayer;
    
    public partial class BillPay
    {
        [Display(Name = "Bill Pay ID")]
        public int BillPayID { get; set; }

        [Required (ErrorMessage = "Account number is required.")]
        [Display(Name = "Account Number")]
        public int AccountNumber { get; set; }

        [Required(ErrorMessage = "Payee ID is required.")]
        [Display(Name = "Payee ID")]
        public int PayeeID { get; set; }

        [Required (ErrorMessage = "Amount is required.")]
        [RegularExpression(@"[-+]?[0-9]*\.?[0-9]?[0-9]", ErrorMessage = "Number required.")]
        public decimal Amount { get; set; }

        [Display(Name = "Schedule Date"), DataType(DataType.Date)]
        [BPayDate(ErrorMessage = "Can not schedule a date in the past.")]
        public System.DateTime ScheduleDate { get; set; }

        [Required(ErrorMessage = "Period is required.")]
        [StringLength(1, MinimumLength = 1, ErrorMessage = "Period cannot be longer than 1 character.")]
        public string Period { get; set; }

        [Display(Name = "Modified Date"), DataType(DataType.Date)]
        public System.DateTime ModifyDate { get; set; }

        public string Status { get; set; }

        [Display(Name = "Stop Date"), DataType(DataType.Date)]
        public Nullable<System.DateTime> StopDate { get; set; }

        [Display(Name = "Stopped By")]
        public string StoppedBy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Payee Payee { get; set; }
    }
}
