//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDTAssignment2NWBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TransactionType
    {
        public TransactionType()
        {
            this.Transactions = new HashSet<Transaction>();
        }

        [Required(ErrorMessage = "Transaction Type ID is required.")]
        [Display(Name = "Transaction Type ID")]
        public int TransactionTypeID { get; set; }

        [Required(ErrorMessage = "Transaction Category ID is required.")]
        [Display(Name = "Transaction Category ID")]
        public int TransactionCategoryID { get; set; }

        [Required(ErrorMessage = "Transaction Type is required.")]
        [StringLength(1, MinimumLength = 1, ErrorMessage = "Transaction type cannot be longer than 1 character.")]
        [Display(Name = "Transaction Type")]
        public string TransactionType1 { get; set; }

        [Display(Name = "Debit/Credit")]
        public string DebitCredit { get; set; }

        public string Description { get; set; }

        [Display(Name = "Modified Date"), DataType(DataType.Date)]
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<Transaction> Transactions { get; set; }
        public virtual TransactionCategory TransactionCategory { get; set; }

        /* Calculated fields. */

        public string TransactionTypeDesc
        {
            get
            {
                string transType = null;
                if (Description == "D")
                {
                    transType = "Deposit";
                }
                else if (Description == "W")
                {
                    transType = "Withdrawal";
                }
                else if (Description == "T")
                {
                    transType = "Transfer";
                }
                else 
                {
                    transType = TransactionType1;
                }
                return "(" + TransactionTypeID + ")" + " " + TransactionType1 + " - " + Description;
            }
        }
    }
}
