//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WDTAssignment2NWBA.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class TransactionCategory
    {
        public TransactionCategory()
        {
            this.TransactionTypes = new HashSet<TransactionType>();
        }

        [Required(ErrorMessage = "Transaction Category ID is required.")]
        [Display(Name = "Transaction Category ID")]
        public int TransactionCategoryID { get; set; }

        [Required(ErrorMessage = "Transaction Category is required.")]
        [Display(Name = "Transaction Category")]
        public string TransactionCategory1 { get; set; }

        public string Description { get; set; }

        [Display(Name = "Modified Date"), DataType(DataType.Date)]
        public Nullable<System.DateTime> ModifyDate { get; set; }
    
        public virtual ICollection<TransactionType> TransactionTypes { get; set; }
    }
}
